spring:
  application:
    name: bielevote-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:./build/bielevote
    username: sa
    password:
  h2.console:
    enabled: true
    settings.web-allow-others: false
    path: /h2-console

app:
  encrypted-password-storage: false
  jwt:
    secret: ?*<JM4T"jL'*7d#kp(S)V`^io9YEhzpSO$[m^D;w=DKY6iw&*#!+J'KGFvJxUM&j
    expiration:
      minutes: 30
  cors:
    allowed-origins: http://localhost:5173/
  proposal-rules:
    max-per-month: 2
    minimum-votes: 3
  project-rules:
    days-voting-active: 30
  reward-rules:
    amount-for-voting: 5
    amount-for-accepted: 100

logging:
  level:
    org.springframework.security: WARN
    # org.hibernate.SQL: DEBUG
