spring:
  application:
    name: bielevote-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:./build/bielevote
    username: sa
    password:
